package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// User represents the structure of a user document in MongoDB
type User struct {
	ID       primitive.ObjectID `bson:"_id,omitempty"` // Automatically generated by MongoDB
	Username string             `bson:"username"`
	Email    string             `bson:"email"`
	Password string             `bson:"password"` // Hashed password
}

type AddUser struct {
	Username string `json:"username" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
}

type LoginUser struct {
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required"`
}
